// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcPHdC5GpQJjSNgc77UeVwARv9pQClpoI',
    appId: '1:984625406508:web:2d25f1034cdb39aa2d6789',
    messagingSenderId: '984625406508',
    projectId: 'well-pass',
    authDomain: 'well-pass.firebaseapp.com',
    storageBucket: 'well-pass.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9_06LBN-EYCY79ertnAA2ygOaKVJLF0s',
    appId: '1:984625406508:android:4518f419183a8f262d6789',
    messagingSenderId: '984625406508',
    projectId: 'well-pass',
    storageBucket: 'well-pass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZd1f9uya1b8iUKvJ574nNxvwXvlQ2UI',
    appId: '1:984625406508:ios:59646e379bd618f62d6789',
    messagingSenderId: '984625406508',
    projectId: 'well-pass',
    storageBucket: 'well-pass.appspot.com',
    iosBundleId: 'com.example.wellPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZd1f9uya1b8iUKvJ574nNxvwXvlQ2UI',
    appId: '1:984625406508:ios:59646e379bd618f62d6789',
    messagingSenderId: '984625406508',
    projectId: 'well-pass',
    storageBucket: 'well-pass.appspot.com',
    iosBundleId: 'com.example.wellPass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcPHdC5GpQJjSNgc77UeVwARv9pQClpoI',
    appId: '1:984625406508:web:8e97921ffbae17462d6789',
    messagingSenderId: '984625406508',
    projectId: 'well-pass',
    authDomain: 'well-pass.firebaseapp.com',
    storageBucket: 'well-pass.appspot.com',
  );
}
